"""Contracts for safe binary map conversion and body-frame placement."""

from array import array
from copy import deepcopy
import math

from geometry_msgs.msg import TransformStamped
from octomap_msgs.msg import Octomap
import pytest

from fault_detector_spot.manipulation.rtabmap_octomap import (
    snapshot_scene_diff,
    validate_binary_occupancy,
)
from fault_detector_spot.shared.geometry.transforms import pose_to_matrix


# Generated by test_octomap_binary_compatibility.cpp from the actual installed
# RTAB-Map subtype at 0.04 m: occupied/free leaves, pruned siblings, unknown gaps.
RTABMAP_BINARY = bytes.fromhex(
    "03fc00c000c000c000c000c000c000c000c000c000c000c03000000c001030003000"
    "300030003000300030003000300030003000300000300c0001000c000c000c000c000"
    "c000c000c000c000c000c000c000c000c000300200003000300030003000300030003"
    "000300030003000300000c30000800"
)


def snapshot():
    result = Octomap()
    result.header.frame_id = "map"
    result.header.stamp.sec = 17
    result.binary = True
    result.id = "ColorOcTree"
    result.resolution = 0.04
    result.data = array("b", RTABMAP_BINARY)
    return result


def placement():
    result = TransformStamped()
    result.header.frame_id = "body"
    result.header.stamp.sec = 21
    result.child_frame_id = "map"
    result.transform.translation.x = 2.0
    result.transform.translation.y = -3.0
    result.transform.translation.z = 0.5
    result.transform.rotation.z = math.sqrt(0.5)
    result.transform.rotation.w = math.sqrt(0.5)
    return result


def test_authentic_rtabmap_binary_is_accepted_with_ros_signed_bytes():
    data = array("b", RTABMAP_BINARY)
    assert len(data) == 118
    assert any(value < 0 for value in data)
    validate_binary_occupancy(data)


@pytest.mark.parametrize(
    "data",
    [
        [],                         # Empty tree.
        [2],                        # Incomplete root header.
        [0, 0],                     # Root with no encoded child state.
        [3, 0],                     # Branch with missing child record.
        [3, 0, 2],                  # Truncated child header.
        [15, 0, 2, 0],              # Two branches, only one supplied.
        [3, 0, 0, 0],               # Empty child record.
        [2, 0, 2, 0],               # Extra unrelated tree after a leaf.
        [3, 0] * 16 + [2, 0],       # Child below OcTree's maximum depth.
        list(RTABMAP_BINARY[:-1]),   # Truncated real serialized tree.
    ],
)
def test_malformed_binary_is_rejected_before_native_decoding(data):
    with pytest.raises(ValueError):
        validate_binary_occupancy(data)


def test_leaf_at_maximum_tree_depth_is_accepted():
    validate_binary_occupancy([3, 0] * 15 + [2, 0])


@pytest.mark.parametrize("tree_id", ["ColorOcTree", "OcTree"])
def test_conversion_normalizes_only_tree_id_and_preserves_binary_and_resolution(tree_id):
    source = snapshot()
    source.id = tree_id

    result = snapshot_scene_diff(source, placement())

    imported = result.world.octomap.octomap
    assert imported.id == "OcTree"
    assert imported.binary
    assert imported.resolution == source.resolution
    assert imported.data == source.data
    assert imported.header == source.header


@pytest.mark.parametrize(
    ("binary", "tree_id"),
    [(False, "ColorOcTree"), (False, "OcTree"), (True, "OtherTree"), (True, "")],
)
def test_full_or_unknown_tree_encoding_is_rejected(binary, tree_id):
    source = snapshot()
    source.binary = binary
    source.id = tree_id
    with pytest.raises(ValueError, match="binary ColorOcTree or OcTree"):
        snapshot_scene_diff(source, placement())


@pytest.mark.parametrize("resolution", [0.0, -0.04, math.inf, -math.inf, math.nan])
def test_invalid_resolution_is_rejected(resolution):
    source = snapshot()
    source.resolution = resolution
    with pytest.raises(ValueError, match="resolution"):
        snapshot_scene_diff(source, placement())


@pytest.mark.parametrize("frame", ["", "odom", "body"])
def test_unexpected_map_frame_is_rejected(frame):
    source = snapshot()
    source.header.frame_id = frame
    with pytest.raises(ValueError, match="OctoMap frame"):
        snapshot_scene_diff(source, placement())


@pytest.mark.parametrize(
    ("target", "source"), [("map", "body"), ("odom", "map"), ("body", "odom")]
)
def test_wrong_or_reversed_transform_is_rejected(target, source):
    transform = placement()
    transform.header.frame_id = target
    transform.child_frame_id = source
    with pytest.raises(ValueError, match="placement transform"):
        snapshot_scene_diff(snapshot(), transform)


def test_custom_map_frame_must_match_both_snapshot_and_transform():
    source = snapshot()
    source.header.frame_id = "site_map"
    transform = placement()
    transform.child_frame_id = "site_map"
    result = snapshot_scene_diff(source, transform, map_frame="site_map")
    assert result.world.octomap.octomap.header.frame_id == "site_map"
    with pytest.raises(ValueError):
        snapshot_scene_diff(source, transform, map_frame="")


@pytest.mark.parametrize("component", ["translation", "rotation"])
@pytest.mark.parametrize("value", [math.nan, math.inf])
def test_nonfinite_transform_is_rejected(component, value):
    transform = placement()
    getattr(transform.transform, component).x = value
    with pytest.raises(ValueError):
        snapshot_scene_diff(snapshot(), transform)


@pytest.mark.parametrize("quaternion", [(0.0, 0.0, 0.0, 0.0), (0.0, 0.0, 0.0, 2.0)])
def test_invalid_transform_quaternion_is_rejected(quaternion):
    transform = placement()
    for axis, value in zip("xyzw", quaternion):
        setattr(transform.transform.rotation, axis, value)
    with pytest.raises(ValueError, match="normalized"):
        snapshot_scene_diff(snapshot(), transform)


def test_origin_applies_body_from_map_translation_and_rotation_exactly_once():
    transform = placement()
    result = snapshot_scene_diff(snapshot(), transform)
    assert result.world.octomap.header == transform.header
    # Map +X becomes body +Y after the 90-degree yaw, followed by translation.
    actual = pose_to_matrix(result.world.octomap.origin) @ [1.0, 0.0, 0.0, 1.0]
    assert actual == pytest.approx([2.0, -2.0, 0.5, 1.0])


def test_scene_diff_does_not_replace_robot_state_objects_or_collision_rules():
    result = snapshot_scene_diff(snapshot(), placement())
    assert result.is_diff
    assert result.robot_state.is_diff
    assert not result.robot_state.joint_state.name
    assert not result.robot_state.multi_dof_joint_state.joint_names
    assert not result.robot_state.attached_collision_objects
    assert not result.world.collision_objects
    assert not result.allowed_collision_matrix.entry_names
    assert not result.allowed_collision_matrix.default_entry_names
    assert not result.link_padding
    assert not result.link_scale
    assert not result.fixed_frame_transforms


def test_input_messages_are_unchanged_and_output_does_not_alias_them():
    source = snapshot()
    transform = placement()
    original_source = deepcopy(source)
    original_transform = deepcopy(transform)

    result = snapshot_scene_diff(source, transform)
    assert source == original_source
    assert transform == original_transform

    result.world.octomap.octomap.header.frame_id = "changed"
    result.world.octomap.octomap.data[0] = 0
    result.world.octomap.header.stamp.sec = 123
    result.world.octomap.origin.position.x = 100.0
    assert source == original_source
    assert transform == original_transform
