slam_toolbox:
  ros__parameters:
    use_sim_time: false
    slam_mode: "localization"

    # Input topics
    scan_topic: /scan
    odom_frame: odom
    map_frame: map
    base_frame: base_link

    # Load previously saved map
    serialization_format: cbor
    map_file_name: /tmp/warehouse_map.db

    # Localization tuning
    resolution: 0.05
    max_laser_range: 50.0
    transform_publish_period: 0.05
    map_update_interval: 4.0
    use_scan_matching: true
    use_pose_graph: false
