slam_toolbox:
  ros__parameters:
    use_sim_time: false
    slam_mode: "mapping"

    # Input topics
    scan_topic: /scan
    odom_frame: odom
    map_frame: map
    base_frame: base_link

    # Optimization / mapping settings
    resolution: 0.05           # grid resolution [m]
    max_laser_range: 50.0
    minimum_time_interval: 0.2
    transform_publish_period: 0.05 # slightly higher to reduce TF overhead
    map_update_interval: 0.4       # updates more frequently without overloading TF
    use_scan_matching: true
    use_scan_barycenter: true
    use_pose_graph: true

    # Serialization
    serialization_format: cbor
    map_file_name: /tmp/warehouse_map.db   # saved pose-graph map
