/**:
  ros__parameters:
    image_transport: raw
    qos_profile: sensor_data

    family: 36h11
    size: 0.1
    max_hamming: 0

    detector:
      threads: 1
      decimate: 1.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false

    pose_estimation_method: "pnp"
