# config/nav2_spot_params.yaml
# Nav2 params for RTAB-Map localization (no AMCL, no map_server)

map_server:
  ros__parameters:
    enabled: false

amcl:
  ros__parameters:
    enabled: false

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: [ "GridBased" ]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.1

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    autostart: false
    controller_plugins: [ "MPPI" ]
    MPPI:
      plugin: "nav2_mppi_controller::MPPIController"
      # Basic MPPI tuning — adjust to your robot
      max_cmd_vel_x: 0.7
      max_cmd_vel_theta: 1.5
      min_cmd_vel_x: -0.2
      acc_lim_x: 1.0
      acc_lim_theta: 3.0
      # planning horizon and sampling (tune for performance)
      time_horizon: 1.5
      time_step: 0.1
      num_samples: 64
      num_elites: 8
      lambda: 1.0
      noise_std_dev_x: 0.15
      noise_std_dev_theta: 0.5
      # safety / goal tolerance
      goal_tolerance: 0.05
      stop_on_goal: true

    # simple goal checker used by the controllers
    goal_checker_plugins: [ "general_goal_checker" ]
    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.1
      stateful: false

# Global costmap subscribes to RTAB-Map's live occupancy grid
global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    static_map: false
    # Subscribe to RTAB-Map's occupancy grid (transient_local recommended)
    map_subscribe_transient_local: true
    topic: /map
    update_frequency: 5.0
    publish_frequency: 1.0
    rolling_window: false
    plugins: [ "static_layer","obstacle_layer","inflation_layer" ]

    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      # observation_sources: <name1> <name2> ...
      observation_sources: jn0_scan frontleft_points frontright_points left_points right_points back_points

      jn0_scan:
        topic: /jn0/base_scan
        expected_update_rate: 20.0
        data_type: LaserScan
        marking: true
        clearing: true

      frontleft_points:
        topic: /depth_registered/frontleft/points
        expected_update_rate: 10.0
        data_type: PointCloud2
        marking: true
        clearing: false

      frontright_points:
        topic: /depth_registered/frontright/points
        expected_update_rate: 10.0
        data_type: PointCloud2
        marking: true
        clearing: false

      left_points:
        topic: /depth_registered/left/points
        expected_update_rate: 10.0
        data_type: PointCloud2
        marking: true
        clearing: false

      right_points:
        topic: /depth_registered/right/points
        expected_update_rate: 10.0
        data_type: PointCloud2
        marking: true
        clearing: false

      back_points:
        topic: /depth_registered/back/points
        expected_update_rate: 10.0
        data_type: PointCloud2
        marking: true
        clearing: false

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.55

# Local costmap (used by controller_server)
local_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 20.0
    rolling_window: true
    width: 6.0
    height: 6.0
    resolution: 0.05
    plugins: [ "voxel_layer","obstacle_layer","inflation_layer" ]

    voxel_layer:
      plugin: "nav2_costmap_2d::VoxelLayer"
      origin_z: 0.0
      z_voxels: 16
      unknown_threshold: 15
      marking_threshold: 0

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: jn0_scan frontleft_points frontright_points left_points right_points back_points

      jn0_scan:
        topic: /jn0/base_scan
        expected_update_rate: 20.0
        data_type: LaserScan
        marking: true
        clearing: true

      frontleft_points:
        topic: /depth_registered/frontleft/points
        expected_update_rate: 10.0
        data_type: PointCloud2
        marking: true
        clearing: false

      frontright_points:
        topic: /depth_registered/frontright/points
        expected_update_rate: 10.0
        data_type: PointCloud2
        marking: true
        clearing: false

      left_points:
        topic: /depth_registered/left/points
        expected_update_rate: 10.0
        data_type: PointCloud2
        marking: true
        clearing: false

      right_points:
        topic: /depth_registered/right/points
        expected_update_rate: 10.0
        data_type: PointCloud2
        marking: true
        clearing: false

      back_points:
        topic: /depth_registered/back/points
        expected_update_rate: 10.0
        data_type: PointCloud2
        marking: true
        clearing: false

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.55

bt_navigator:
  ros__parameters:
    autostart: false
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"