from enum import Enum


class CommandID(str, Enum):
    EXECUTE_PROBE_POINT = "execute_probe_point"
    STOW_ARM = "stow_arm"
    READY_ARM = "ready_arm"
    READY_SAFE_APPROACH = "probe_setup_ready_safe_approach"
    MOVE_SAFE_APPROACH = "probe_setup_move_safe_approach"
    ADJUST_SAFE_APPROACH = "probe_setup_adjust_safe_approach"
    FOLLOW_MOVE_TO_TAG_PATH = "follow_move_to_tag_path"
    MOVE_ARM_TO_TAG = "move_to_tag"
    MOVE_ARM_TO_TAG_AND_WAIT = "move_tag_and_wait"
    MOVE_ARM_RELATIVE = "move_arm_relative"
    MOVE_CLOSE_TO_SURFACE = "move_close_to_surface"
    ORIENT_TO_SURFACE = "orient_to_surface"
    ORIENT_TO_TAG = "orient_to_tag"
    CHANGE_BODY_HEIGHT = "change_body_height"
    STAND_UP = "stand_up"
    SIT_DOWN = "sit_down"
    WAIT_TIME = "wait_time"
    EMERGENCY_CANCEL = "cancel_all"
    TOGGLE_GRIPPER = "toggle_gripper"
    CLOSE_GRIPPER = "close_gripper"
    ESTOP_STATE = "estop_state"
    STOP_BASE = "stop_base"
    START_SLAM = "start_slam"
    START_LOCALIZATION = "start_localization"
    STOP_MAPPING = "stop_mapping"
    SWAP_MAP = "swap_map"
    MOVE_TO_WAYPOINT = "move_to_waypoint"
    MOVE_BASE_TO_TAG = "move_base_to_tag"
    MOVE_BASE_RELATIVE = "move_base_relative"
    START_SENSOR_RECORDING = "start_sensor_recording"
    STOP_SENSOR_RECORDING = "stop_sensor_recording"
